"""llminspector — end-to-end LLM evaluation toolkit.

Public API (populated incrementally across the refactor phases):
    evaluate, LLMTestCase, EvaluationDataset, Golden,
    metric classes, synthesizers, Settings, __version__

Phase 0 lays down the empty package tree; each subsequent phase ports the
corresponding layer from the legacy ``llm_inspector`` package.
"""

try:
    from .version import __version__, __version_date__
except ImportError:  # version.py is generated by pydnx at build time
    __version__ = None
    __version_date__ = ""

from .config import Settings
from .dataset import EvaluationDataset, Golden
from .models import (
    AzureOpenAIEmbedding,
    AzureOpenAIModel,
    BaseEmbeddingModel,
    BaseLLM,
)
from .test_case import LLMTestCase

__all__ = [
    "__version__",
    "__version_date__",
    "LLMTestCase",
    "EvaluationDataset",
    "Golden",
    "Settings",
    "BaseLLM",
    "BaseEmbeddingModel",
    "AzureOpenAIModel",
    "AzureOpenAIEmbedding",
]
