"""llminspector — end-to-end LLM evaluation toolkit.

Public API (populated incrementally across the refactor phases):
    evaluate, LLMTestCase, EvaluationDataset, Golden,
    metric classes, synthesizers, Settings, __version__

The public surface below spans the schema, model, metrics, evaluate,
synthesizer, and reporting layers.
"""

try:
    from .version import __version__, __version_date__
except ImportError:  # version.py is generated by pydnx at build time
    __version__ = None
    __version_date__ = ""

from . import metrics
from .config import Settings
from .dataset import EvaluationDataset, Golden
from .evaluate import EvaluationResult, evaluate
from .metrics import (
    AnswerCorrectnessMetric,
    AnswerJailbreakMetric,
    AnswerRelevancyMetric,
    BaseMetric,
    BertScoreMetric,
    CodeDetectMetric,
    ConcisenessMetric,
    ContentModerationMetric,
    ContextEntityRecallMetric,
    ContextPrecisionMetric,
    ContextRecallMetric,
    ContextRelevanceMetric,
    ContextUtilisationMetric,
    EmotionMetric,
    FaithfulnessMetric,
    HallucinationMetric,
    LanguageDetectionMetric,
    PIIDetectionMetric,
    PolicyComplianceMetric,
    QuestionJailbreakMetric,
    ReadabilityMetric,
    RefusalMetric,
    SentimentMetric,
    TokenCountMetric,
)
from . import reporting
from .models import (
    AzureOpenAIEmbedding,
    AzureOpenAIModel,
    BaseEmbeddingModel,
    BaseLLM,
)
from .synthesizer import (
    AdversarialSynthesizer,
    AlignmentSynthesizer,
    BaseSynthesizer,
    RagSynthesizer,
)
from .test_case import LLMTestCase

__all__ = [
    "__version__",
    "__version_date__",
    "LLMTestCase",
    "EvaluationDataset",
    "Golden",
    "Settings",
    "evaluate",
    "EvaluationResult",
    "BaseLLM",
    "BaseEmbeddingModel",
    "AzureOpenAIModel",
    "AzureOpenAIEmbedding",
    "metrics",
    "BaseMetric",
    "BertScoreMetric",
    "FaithfulnessMetric",
    "AnswerCorrectnessMetric",
    "AnswerRelevancyMetric",
    "ConcisenessMetric",
    "ContextPrecisionMetric",
    "ContextRecallMetric",
    "ContextUtilisationMetric",
    "ContextRelevanceMetric",
    "ContextEntityRecallMetric",
    "PIIDetectionMetric",
    "ContentModerationMetric",
    "QuestionJailbreakMetric",
    "AnswerJailbreakMetric",
    "RefusalMetric",
    "HallucinationMetric",
    "CodeDetectMetric",
    "SentimentMetric",
    "EmotionMetric",
    "LanguageDetectionMetric",
    "ReadabilityMetric",
    "TokenCountMetric",
    "PolicyComplianceMetric",
    "BaseSynthesizer",
    "AlignmentSynthesizer",
    "AdversarialSynthesizer",
    "RagSynthesizer",
    "reporting",
]
